/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Gateways: () => import('#controllers/gateways_controller'),
  Users: () => import('#controllers/users_controller'),
}
